
CREATE TABLE users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('ROLE_DRIVER', 'ROLE_FIREFIGHTER', 'ROLE_SERGEANT', 'ROLE_B3', 'ROLE_OFFICER')),
  name TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE modules (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  type TEXT NOT NULL CHECK (type IN ('FUEL', 'CHECKLIST', 'PASS_ALONG', 'DEJEM', 'DEA')),
  status TEXT NOT NULL DEFAULT 'AWAITING_SERGEANT' CHECK (status IN ('AWAITING_SERGEANT', 'VALIDATED_SERGEANT', 'REVIEWED_B3', 'PUBLISHED_OFFICERS')),
  payload TEXT NOT NULL,
  created_by TEXT NOT NULL,
  validated_by TEXT,
  reviewed_by TEXT,
  published_by TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (validated_by) REFERENCES users(id),
  FOREIGN KEY (reviewed_by) REFERENCES users(id),
  FOREIGN KEY (published_by) REFERENCES users(id)
);
